name: CI Tests/Lints

on:
  push:
    paths:
      - "termynal/**"
      - "tests/**"
      - "poetry.lock"
    branches: [ main ]
  pull_request:
    paths:
      - "termynal/**"
      - "tests/**"
      - "poetry.lock"
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install python dependencies
        run: make install-poetry install

      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install python dependencies
        run: make install-poetry install

      - name: Run test
        run: make test
